---
apiVersion: v1
kind: Service
metadata:
  name: game-server-service
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: game-server
          image: go-code-breaker:latest
          ports:
            - containerPort: 8080
          command: ["./game", "server"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-client
  template:
    metadata:
      labels:
        app: game-client
    spec:
      containers:
        - name: game-client
          image: go-game-client:latest
          command: ["./client", "client"]
          stdin: true
          tty: true